kind: pipeline
type: docker
name: plantuml
trigger:
  branch:
  - main
  - master
  event:
  - push

steps:
  - name: lint & render all .puml files
    image: plantuml/plantuml
    pull: if-not-exists
    commands:
      - find . -type f -name "*.puml" -exec sh -c 'cat "$1" | java -jar /opt/plantuml.jar -tsvg -pipe > $(dirname "$1")/$(basename "$1" .puml).svg' _ {} \;
