@startuml test

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "user", "")
System_Boundary(system, "System", "") {
    Container(fe, "frontend", "")
    Container(be, "backend", "")
    Container(db, "database", "")
}

BiRel(user, fe, "uses")
BiRel(fe, be, "request", "http")
BiRel(be, db, "crud")

@enduml
